/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as HrIndexRouteImport } from './routes/hr.index'
import { Route as CandidateIndexRouteImport } from './routes/candidate.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as HrSettingsRouteImport } from './routes/hr.settings'
import { Route as HrReportsRouteImport } from './routes/hr.reports'
import { Route as HrPostJobRouteImport } from './routes/hr.post-job'
import { Route as HrJobsRouteImport } from './routes/hr.jobs'
import { Route as HrInterviewsRouteImport } from './routes/hr.interviews'
import { Route as HrCandidatesRouteImport } from './routes/hr.candidates'
import { Route as HrApplicationsRouteImport } from './routes/hr.applications'
import { Route as HrAnalyticsRouteImport } from './routes/hr.analytics'
import { Route as CandidateSettingsRouteImport } from './routes/candidate.settings'
import { Route as CandidateResumeRouteImport } from './routes/candidate.resume'
import { Route as CandidateRecommendedRouteImport } from './routes/candidate.recommended'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateNotificationsRouteImport } from './routes/candidate.notifications'
import { Route as CandidateMatchRouteImport } from './routes/candidate.match'
import { Route as CandidateInterviewsRouteImport } from './routes/candidate.interviews'
import { Route as CandidateAppliedRouteImport } from './routes/candidate.applied'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRecruitersRouteImport } from './routes/admin.recruiters'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as JobsJobIdApplyRouteImport } from './routes/jobs.$jobId.apply'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrIndexRoute = HrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const HrSettingsRoute = HrSettingsRouteImport.update({
  id: '/hr/settings',
  path: '/hr/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HrReportsRoute = HrReportsRouteImport.update({
  id: '/hr/reports',
  path: '/hr/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPostJobRoute = HrPostJobRouteImport.update({
  id: '/hr/post-job',
  path: '/hr/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const HrJobsRoute = HrJobsRouteImport.update({
  id: '/hr/jobs',
  path: '/hr/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HrInterviewsRoute = HrInterviewsRouteImport.update({
  id: '/hr/interviews',
  path: '/hr/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const HrCandidatesRoute = HrCandidatesRouteImport.update({
  id: '/hr/candidates',
  path: '/hr/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const HrApplicationsRoute = HrApplicationsRouteImport.update({
  id: '/hr/applications',
  path: '/hr/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const HrAnalyticsRoute = HrAnalyticsRouteImport.update({
  id: '/hr/analytics',
  path: '/hr/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateSettingsRoute = CandidateSettingsRouteImport.update({
  id: '/candidate/settings',
  path: '/candidate/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateResumeRoute = CandidateResumeRouteImport.update({
  id: '/candidate/resume',
  path: '/candidate/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRecommendedRoute = CandidateRecommendedRouteImport.update({
  id: '/candidate/recommended',
  path: '/candidate/recommended',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateNotificationsRoute = CandidateNotificationsRouteImport.update({
  id: '/candidate/notifications',
  path: '/candidate/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateMatchRoute = CandidateMatchRouteImport.update({
  id: '/candidate/match',
  path: '/candidate/match',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateInterviewsRoute = CandidateInterviewsRouteImport.update({
  id: '/candidate/interviews',
  path: '/candidate/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAppliedRoute = CandidateAppliedRouteImport.update({
  id: '/candidate/applied',
  path: '/candidate/applied',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecruitersRoute = AdminRecruitersRouteImport.update({
  id: '/admin/recruiters',
  path: '/admin/recruiters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/admin/candidates',
  path: '/admin/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdApplyRoute = JobsJobIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JobsJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/recruiters': typeof AdminRecruitersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/applied': typeof CandidateAppliedRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/match': typeof CandidateMatchRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/recommended': typeof CandidateRecommendedRoute
  '/candidate/resume': typeof CandidateResumeRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/hr/analytics': typeof HrAnalyticsRoute
  '/hr/applications': typeof HrApplicationsRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/interviews': typeof HrInterviewsRoute
  '/hr/jobs': typeof HrJobsRoute
  '/hr/post-job': typeof HrPostJobRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/hr/': typeof HrIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/recruiters': typeof AdminRecruitersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/applied': typeof CandidateAppliedRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/match': typeof CandidateMatchRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/recommended': typeof CandidateRecommendedRoute
  '/candidate/resume': typeof CandidateResumeRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/hr/analytics': typeof HrAnalyticsRoute
  '/hr/applications': typeof HrApplicationsRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/interviews': typeof HrInterviewsRoute
  '/hr/jobs': typeof HrJobsRoute
  '/hr/post-job': typeof HrPostJobRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/candidate': typeof CandidateIndexRoute
  '/hr': typeof HrIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/recruiters': typeof AdminRecruitersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/applied': typeof CandidateAppliedRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/match': typeof CandidateMatchRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/recommended': typeof CandidateRecommendedRoute
  '/candidate/resume': typeof CandidateResumeRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/hr/analytics': typeof HrAnalyticsRoute
  '/hr/applications': typeof HrApplicationsRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/interviews': typeof HrInterviewsRoute
  '/hr/jobs': typeof HrJobsRoute
  '/hr/post-job': typeof HrPostJobRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/hr/': typeof HrIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/companies'
    | '/contact'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/admin/candidates'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/recruiters'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/applied'
    | '/candidate/interviews'
    | '/candidate/match'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/recommended'
    | '/candidate/resume'
    | '/candidate/settings'
    | '/hr/analytics'
    | '/hr/applications'
    | '/hr/candidates'
    | '/hr/interviews'
    | '/hr/jobs'
    | '/hr/post-job'
    | '/hr/reports'
    | '/hr/settings'
    | '/jobs/$jobId'
    | '/admin/'
    | '/candidate/'
    | '/hr/'
    | '/jobs/'
    | '/jobs/$jobId/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/companies'
    | '/contact'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/admin/candidates'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/recruiters'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/applied'
    | '/candidate/interviews'
    | '/candidate/match'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/recommended'
    | '/candidate/resume'
    | '/candidate/settings'
    | '/hr/analytics'
    | '/hr/applications'
    | '/hr/candidates'
    | '/hr/interviews'
    | '/hr/jobs'
    | '/hr/post-job'
    | '/hr/reports'
    | '/hr/settings'
    | '/jobs/$jobId'
    | '/admin'
    | '/candidate'
    | '/hr'
    | '/jobs'
    | '/jobs/$jobId/apply'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/companies'
    | '/contact'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/admin/candidates'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/recruiters'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/applied'
    | '/candidate/interviews'
    | '/candidate/match'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/recommended'
    | '/candidate/resume'
    | '/candidate/settings'
    | '/hr/analytics'
    | '/hr/applications'
    | '/hr/candidates'
    | '/hr/interviews'
    | '/hr/jobs'
    | '/hr/post-job'
    | '/hr/reports'
    | '/hr/settings'
    | '/jobs/$jobId'
    | '/admin/'
    | '/candidate/'
    | '/hr/'
    | '/jobs/'
    | '/jobs/$jobId/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminRecruitersRoute: typeof AdminRecruitersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CandidateAppliedRoute: typeof CandidateAppliedRoute
  CandidateInterviewsRoute: typeof CandidateInterviewsRoute
  CandidateMatchRoute: typeof CandidateMatchRoute
  CandidateNotificationsRoute: typeof CandidateNotificationsRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateRecommendedRoute: typeof CandidateRecommendedRoute
  CandidateResumeRoute: typeof CandidateResumeRoute
  CandidateSettingsRoute: typeof CandidateSettingsRoute
  HrAnalyticsRoute: typeof HrAnalyticsRoute
  HrApplicationsRoute: typeof HrApplicationsRoute
  HrCandidatesRoute: typeof HrCandidatesRoute
  HrInterviewsRoute: typeof HrInterviewsRoute
  HrJobsRoute: typeof HrJobsRoute
  HrPostJobRoute: typeof HrPostJobRoute
  HrReportsRoute: typeof HrReportsRoute
  HrSettingsRoute: typeof HrSettingsRoute
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  HrIndexRoute: typeof HrIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/': {
      id: '/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof HrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/settings': {
      id: '/hr/settings'
      path: '/hr/settings'
      fullPath: '/hr/settings'
      preLoaderRoute: typeof HrSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/reports': {
      id: '/hr/reports'
      path: '/hr/reports'
      fullPath: '/hr/reports'
      preLoaderRoute: typeof HrReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/post-job': {
      id: '/hr/post-job'
      path: '/hr/post-job'
      fullPath: '/hr/post-job'
      preLoaderRoute: typeof HrPostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/jobs': {
      id: '/hr/jobs'
      path: '/hr/jobs'
      fullPath: '/hr/jobs'
      preLoaderRoute: typeof HrJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/interviews': {
      id: '/hr/interviews'
      path: '/hr/interviews'
      fullPath: '/hr/interviews'
      preLoaderRoute: typeof HrInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/candidates': {
      id: '/hr/candidates'
      path: '/hr/candidates'
      fullPath: '/hr/candidates'
      preLoaderRoute: typeof HrCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/applications': {
      id: '/hr/applications'
      path: '/hr/applications'
      fullPath: '/hr/applications'
      preLoaderRoute: typeof HrApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/analytics': {
      id: '/hr/analytics'
      path: '/hr/analytics'
      fullPath: '/hr/analytics'
      preLoaderRoute: typeof HrAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/settings': {
      id: '/candidate/settings'
      path: '/candidate/settings'
      fullPath: '/candidate/settings'
      preLoaderRoute: typeof CandidateSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/resume': {
      id: '/candidate/resume'
      path: '/candidate/resume'
      fullPath: '/candidate/resume'
      preLoaderRoute: typeof CandidateResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/recommended': {
      id: '/candidate/recommended'
      path: '/candidate/recommended'
      fullPath: '/candidate/recommended'
      preLoaderRoute: typeof CandidateRecommendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/notifications': {
      id: '/candidate/notifications'
      path: '/candidate/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof CandidateNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/match': {
      id: '/candidate/match'
      path: '/candidate/match'
      fullPath: '/candidate/match'
      preLoaderRoute: typeof CandidateMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/interviews': {
      id: '/candidate/interviews'
      path: '/candidate/interviews'
      fullPath: '/candidate/interviews'
      preLoaderRoute: typeof CandidateInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/applied': {
      id: '/candidate/applied'
      path: '/candidate/applied'
      fullPath: '/candidate/applied'
      preLoaderRoute: typeof CandidateAppliedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recruiters': {
      id: '/admin/recruiters'
      path: '/admin/recruiters'
      fullPath: '/admin/recruiters'
      preLoaderRoute: typeof AdminRecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/admin/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/apply': {
      id: '/jobs/$jobId/apply'
      path: '/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof JobsJobIdApplyRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
  }
}

interface JobsJobIdRouteChildren {
  JobsJobIdApplyRoute: typeof JobsJobIdApplyRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdApplyRoute: JobsJobIdApplyRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminRecruitersRoute: AdminRecruitersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CandidateAppliedRoute: CandidateAppliedRoute,
  CandidateInterviewsRoute: CandidateInterviewsRoute,
  CandidateMatchRoute: CandidateMatchRoute,
  CandidateNotificationsRoute: CandidateNotificationsRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateRecommendedRoute: CandidateRecommendedRoute,
  CandidateResumeRoute: CandidateResumeRoute,
  CandidateSettingsRoute: CandidateSettingsRoute,
  HrAnalyticsRoute: HrAnalyticsRoute,
  HrApplicationsRoute: HrApplicationsRoute,
  HrCandidatesRoute: HrCandidatesRoute,
  HrInterviewsRoute: HrInterviewsRoute,
  HrJobsRoute: HrJobsRoute,
  HrPostJobRoute: HrPostJobRoute,
  HrReportsRoute: HrReportsRoute,
  HrSettingsRoute: HrSettingsRoute,
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  HrIndexRoute: HrIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
